# Site settings
name: name
email: email

description: "A blog and a portfolio"
author: "author"
title: "2조 전윤태"
permalink: pretty
baseurl: /jekyll-theme-blogfolio
url: "https://jeonyuntae.github.io"

github:
  username: username

twitter:
  username: username
