# Site settings
name: 전윤태
email: jyt0131@gmail.com

description: "A blog and a portfolio"
author: "author"
title: "2조 전윤태"
permalink: pretty
baseurl:
url: "https://jeonyuntae.github.io"

github:
  username: JEONYUNTAE

twitter:
  username: username
